<?php
// $Id$

// Codes used for countries in the original data.
define('POSTNUMRE_DENMARK', 1);
define('POSTNUMRE_GREENLAND', 2);
define('POSTNUMRE_FAROE', 3);

/**
 * @file postnumre.module
 * Helper module for Danish postal codes.
 *
 * Providing a few functions and an AHAH callback for dealing with
 * the 1400+ postal codes used in the Kingdom of Denmark.
 */

/**
 * Look up a postal code.
 *
 * @param mixed $input
 *    Input, typically string or int.
 * @param int $restrict_country
 *    Restrict the search to a single country. Default is Danish postal codes only.
 * @return mixed object|bool
 *    If a code was found, the postal code object, if not boolean FALSE.
 */
function postnumre_validate_code($input, $restrict_country = POSTNUMRE_DENMARK) {
  if (is_numeric($input)) {
    $query = db_query("SELECT * FROM {postnumre} WHERE CODE = %d LIMIT 1", $input);
    if ($query) {
      return db_fetch_object($query);
    }
  }
  return FALSE;
}

